name: Deploy PROD (OlmeraOT)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-prod-olmeraot
  cancel-in-progress: false

env:
  CORE_ZIP_URL_PROD: ${{ vars.CORE_ZIP_URL_PROD }}
  CORE_SHA_URL_PROD: ${{ vars.CORE_SHA_URL_PROD }}

jobs:
  deploy:
    name: Deploy to PROD (VPS)
    runs-on: ubuntu-latest

    steps:
      - name: (Opcional) Establecer known_hosts
        run: |
          mkdir -p ~/.ssh
          if [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ]; then
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
          else
            echo "No SSH_KNOWN_HOSTS provided; skipping."
          fi

      - name: SSH into VPS and stage binary (no restart)
        uses: appleboy/ssh-action@v1.2.0
        env:
          CORE_ZIP_URL_PROD: ${{ env.CORE_ZIP_URL_PROD }}
          CORE_SHA_URL_PROD: ${{ env.CORE_SHA_URL_PROD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CORE_ZIP_URL_PROD,CORE_SHA_URL_PROD
          script_stop: true
          script: |
            set -euo pipefail

            echo "[PROD] Deploy (sin restart) en ${{ secrets.VPS_PROD_PATH }}"
            cd "${{ secrets.VPS_PROD_PATH }}"

            echo "[PROD] Sync código (main + submodules)"
            git fetch --all --prune
            git checkout main
            git reset --hard origin/main
            git submodule sync --recursive
            git submodule update --init --recursive --remote

            echo "[PROD] Render config"
            /usr/local/bin/olmera-render-config prod

            BIN_DIR="/opt/olmeraot/prod/bin"
            BIN_PATH="${BIN_DIR}/olmeraot"
            SHA_MARKER="${BIN_DIR}/OLMERAOT_ZIP_SHA"

            mkdir -p "${BIN_DIR}"

            echo "[PROD] Descargando SHA remoto"
            curl -fsSL -o /tmp/SHA256SUMS "$CORE_SHA_URL_PROD"
            REMOTE_SHA="$(awk '{print $1}' /tmp/SHA256SUMS)"
            LOCAL_SHA="$(cat "${SHA_MARKER}" 2>/dev/null || true)"

            if [ -n "${LOCAL_SHA}" ] && [ "${LOCAL_SHA}" = "${REMOTE_SHA}" ] && [ -x "${BIN_PATH}" ]; then
              echo "[PROD] Binario ya actualizado (SHA coincide). No se descarga ZIP."
            else
              echo "[PROD] Descargando ZIP nuevo"
              curl -fsSL -o /tmp/olmeraot.zip "$CORE_ZIP_URL_PROD"

              echo "[PROD] Verificando ZIP con SHA256SUMS"
              pushd /tmp >/dev/null
              sha256sum --ignore-missing -c /tmp/SHA256SUMS
              popd >/dev/null

              echo "[PROD] Descomprimiendo ZIP al bin dir"
              unzip -o /tmp/olmeraot.zip -d "${BIN_DIR}"
              chmod +x "${BIN_PATH}"
              echo "${REMOTE_SHA}" > "${SHA_MARKER}"
            fi

            echo "[PROD] Listo. (Sin reiniciar servicio automáticamente)"
            systemctl --no-pager --lines=3 status olmeraot-prod.service || true
