name: CI-CD

on:
  push:
    branches: [develop, main]
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write   # publicar en GHCR

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Compute TAG
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "branch" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build image (infra/Dockerfile.olmera, amd64)
        run: |
          docker build \
            --platform linux/amd64 \
            -f infra/Dockerfile.olmera \
            -t ghcr.io/edmundoc90/olmera:${{ steps.vars.outputs.TAG }} \
            .

      - name: Push image
        run: |
          docker push ghcr.io/edmundoc90/olmera:${{ steps.vars.outputs.TAG }}
          if [[ "${{ steps.vars.outputs.TAG }}" == "main" || "${GITHUB_REF_TYPE}" == "tag" ]]; then
            docker tag ghcr.io/edmundoc90/olmera:${{ steps.vars.outputs.TAG }} ghcr.io/edmundoc90/olmera:latest
            docker push ghcr.io/edmundoc90/olmera:latest
          fi

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "${GITHUB_REF_NAME}" = "develop" ]; then
              cd /home/olmeraot/olmera-develop
              docker compose -f docker-compose.develop.yml pull
              docker compose -f docker-compose.develop.yml up -d --remove-orphans
            elif [ "${GITHUB_REF_NAME}" = "main" ] || [ "${GITHUB_REF_TYPE}" = "tag" ]; then
              cd /home/olmeraot/olmera-main
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d --remove-orphans
            fi
