name: Promote QA Binary to Prod (Manual)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Motivo/nota del promote (opcional)"
        required: false
        default: ""

concurrency:
  group: promote-qa-to-prod
  cancel-in-progress: false

permissions:
  contents: write   # Necesario para leer descargas y publicar/actualizar releases

jobs:
  promote:
    name: Promote QA→PROD
    runs-on: ubuntu-latest
    env:
      QA_TAG: qa-latest
      PROD_TAG: prod-latest
    steps:
      - name: Checkout (requerido por algunas actions)
        uses: actions/checkout@v4

      - name: Descargar assets desde QA (qa-latest)
        uses: dawidd6/action-download-release@v2
        with:
          tag: ${{ env.QA_TAG }}
          repo: ${{ github.repository }}
          file: |
            olmeraot-linux-x86_64.zip
            SHA256SUMS

      # (Opcional) Verificar que ambos archivos existen y tienen tamaño > 0
      - name: Validar archivos descargados
        run: |
          ls -l
          test -s "olmeraot-linux-x86_64.zip"
          test -s "SHA256SUMS"

      # (Opcional recomendado) Borrar assets previos del release prod-latest para evitar duplicados
      - name: Eliminar assets previos de PROD
        uses: svenstaro/delete-release-assets@v1
        with:
          tag: ${{ env.PROD_TAG }}
          assets: |
            olmeraot-linux-x86_64.zip
            SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publicar/actualizar release de PROD con los mismos assets
      - name: Publicar en PROD (prod-latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PROD_TAG }}
          name: PROD Latest
          body: |
            Promoted from ${{ env.QA_TAG }} by ${{ github.actor }}.
            Commit source: ${{ github.sha }}
            Reason: ${{ github.event.inputs.reason }}
          draft: false
          prerelease: false
          files: |
            olmeraot-linux-x86_64.zip
            SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mostrar resumen
        run: |
          echo "Promoted QA ($QA_TAG) → PROD ($PROD_TAG)"
          sha256sum olmeraot-linux-x86_64.zip || true
